<div>
    <h1 class="title">FAQ > Basics</h1>
    <div class="common-box">
        <h1 class="subtitle">How do I Post Anonymously?</h1>
        <div class="padding-left-40">
            To post as "Anonymous", simply do not fill in the [Name] field when submitting content. Information such as your personal IP address is viewable only to the administrators, and is not made publicly available.
        </div>
    </div>
    <div class="common-box">
        <h1 class="subtitle">Can I register a username?</h1>
        <div class="padding-left-40">
            No user registration process is available. If you're worried about somebody impersonating you, consider using a tripcode to help validate your identity.
        </div>
    </div>
    <div class="common-box">
        <h1 class="subtitle">Must I post an image?</h1>
        <div class="padding-left-40">
            To start a new thread, you must upload an image. 4chan isprimarily an imageboard after all! When replying to an already existing thread, no attachment is required.
        </div>
    </div>
    <div class="common-box">
        <h1 class="subtitle">Can I reply with an image?</h1>
        <div class="padding-left-40">
            Yes. To reply to a thread with an image of your own, click the [Reply] link and fill in the post box as you normally would, making sure to specify an image for attachment.
        </div>
    </div>
    <div class="common-box">
        <h1 class="subtitle">How do I quote somebody?</h1>
        <div class="padding-left-40">
            To quote a portion of text, simply place a pointer (">") in front of the text you wish to highlight (ex. ">This is a quote"). To link to and highlight an entire post, place two pointers in front of its unique post number (ex. ">>210981"). Cross-linking to another 4chan board is also possible, by placing three pointers before a board letter, followed by a post number (ex. ">>>/x/1208196").
            <br/><br/>If you're using our inline extension, simply click the post number you'd like to reference and it will bring up a Quick Reply window for you to write your response in. Highlighting text and then clicking the post number will quote the selected text.
        </div>
    </div>
    <div class="common-box">
        <h1 class="subtitle">Can I mark a submission as a spoiler?</h1>
        <div class="padding-left-40">
            Only certain boards allow you to mask plot-spoiling content. To mark your image as a spoiler, check the [x Spoiler Image?] box before submission. Spoilerizing text makes it unreadable to others until they mouse over it. To spoilerize a comment, place [spoiler] tags around the text you wish to hide (ex. "[spoiler]SPIKE DIES![/spoiler]"). Misuse of these tags may result in a ban.
        </div>
    </div>
    <div class="common-box">
        <h1 class="subtitle">How do I use a "tripcode"?
        </h1>
        <div class="padding-left-40">
            Tripcodes can help verify a user's identity to others, and are a type of pseudo-registration. To use a normal tripcode, place a hash mark ("#") followed by a word or short phrase after what you've entered into the [Name] field (ex. "User#password"). Upon submission, the server will generate the hash unique to that particular word or phrase. The previous example would display "User!ozOtJW9BFA" after being posted.
            <br/><br/>Important note: A tripcode is generated only using the text entered after the hash mark. Your entered name, IP address, cookie information, etc. do not affect the output. Normal tripcodes are not secure, and can be cracked with relative ease. For a more secure solution, see secure tripcodes.
        </div>
    </div>
    <div class="common-box">
        <h1 class="subtitle">What is a "secure tripcode"?
        </h1>
        <div class="padding-left-40">
            A secure tripcode can be generated by placing two hash marks in the [Name] field, as opposed to one as with anormal tripcode (ex. "User##password"). Secure tripcodes use a secret key file on the server to help obscure their password. The previous example would display "User!!rEkSWzi2+mz" after being posted.
        </div>
    </div>
</div>